export const messages = {
 en: {
  common:{products:"Products",how:"How it works",demo:"Demo",pricing:"Pricing",faq:"FAQ",book:"Book a demo",live:"Live",soon:"Coming Soon",learn:"Explore product",home:"Home"},
  home:{badge:"AI LEADFLOW",values:["Instant Response","Smart Qualification","Sales Ready"],title:"Reply late.",accent:"Lose deals.",supporting:"AI LeadFlow replies to customers, identifies buying intent, updates your CRM, and sends high-intent opportunities straight to sales.",primary:"See How It Works",secondary:"Book Free Demo",pipeline:"One intelligent pipeline",salesperson:"Your best salesperson never sleeps.",pipelineCopy:"AI LeadFlow replies to every inquiry, records it in your CRM, and alerts sales when a customer is ready to buy.",problem:"The hidden revenue leak",problemTitle:"Your leads aren’t the problem. Your response time is.",problems:[["5+ hrs","Leads wait too long","Interested customers go cold while your team is busy doing everything else."],["42%","Follow-ups get missed","Manual handoffs and scattered inboxes make consistent follow-up nearly impossible."],["No signal","Every lead looks equal","Your best opportunities are buried in a queue with everyone else."]],results:"AI handles the repetitive work.\nSales focuses on closing.",resultCards:[["Faster","Customers get a response without waiting hours."],["Smarter","Sales knows exactly who deserves attention first."],["Less manual work","No more manually sorting, recording and chasing every inquiry."]],howTitle:"From customer message to sales handoff.\nAutomatically.",howCopy:"",steps:[["01","Customer reaches out","A new inquiry arrives from your website, ads, WhatsApp, email or forms."],["02","AI understands intent","AI analyzes needs, budget, timing and buying signals."],["03","Reply + CRM update","A personalized response is created and the CRM is updated automatically."],["04","Best opportunities go to sales","High-intent customers are immediately surfaced to the sales team."]],demoTitle:"Watch a lead qualify itself.",demoCopy:"Choose an answer and see AI LeadFlow update the opportunity in real time.",video:"90 seconds to a smarter pipeline.",pricingTitle:"Start focused. Scale freely.",pricingCopy:"Every LeadFlow workspace is configured around your funnel—not a generic template.",faqTitle:"Questions, answered.",cta:"See what AI LeadFlow can do for your pipeline.",ctaCopy:"A focused 30-minute walkthrough, configured around your actual sales process."},
  products:{eyebrow:"AI systems, built to compound",title:"A product suite for the work that moves business forward.",intro:"Purpose-built AI products that remove operational friction, surface better decisions, and let your people focus on work only people can do.",suite:"The product suite",suiteTitle:"Start with one workflow. Build an intelligent company.",cards:[{name:"AI LeadFlow",tag:"Revenue intelligence",desc:"Qualify, score and follow up with every lead instantly—then route sales-ready opportunities with full context.",points:["Instant qualification","Intent scoring","Automated follow-up"],live:true},{name:"AI Recruitment",tag:"Talent intelligence",desc:"Find, screen and coordinate exceptional candidates with a hiring system that never loses momentum.",points:["Candidate screening","Smart shortlists","Interview orchestration"],live:false},{name:"AI Customer Support",tag:"Service intelligence",desc:"Resolve routine questions instantly and give your team the context to handle every complex conversation.",points:["Always-on resolution","Intelligent routing","Unified context"],live:false},{name:"AI Invoice Automation",tag:"Finance operations",desc:"Capture, validate and route invoices automatically, with transparent controls at every step.",points:["Data extraction","Approval workflows","Exception detection"],live:false}],platform:"One intelligent foundation",platformTitle:"Designed as a system. Not a collection of tools.",platformCopy:"Every product shares a scalable architecture for integrations, intelligence, governance and reporting—so each new workflow makes your operation stronger.",pillars:[["01","Connect everywhere","Fit into the systems your teams already trust."],["02","Learn continuously","Turn every interaction into better operational intelligence."],["03","Scale responsibly","Keep humans in control with clear rules and visibility."]],cta:"Build your AI operating layer.",ctaCopy:"Start with the workflow creating the most friction today. We’ll design the path forward."},footer:"Built with AI. Designed for people."},
 zh:{
  common:{products:"产品",how:"如何运作",demo:"现场体验",pricing:"方案",faq:"问答",book:"预约演示",live:"现已开放",soon:"敬请期待",learn:"了解产品",home:"首页"},
  home:{badge:"AI LEADFLOW",values:["⚡ 即时回复","🎯 自动筛选","📈 销售跟进"],title:"回应慢了",accent:"成交没了",supporting:"AI 自动回复客户、判断成交意向、更新 CRM，并把高意向客户直接交给销售",primary:"查看 AI 如何工作",secondary:"预约免费体验",pipeline:"从兴趣到行动",salesperson:"机会来了\n不必再等",pipelineCopy:"AI 自动回复每一条咨询、更新 CRM，并在客户准备购买时提醒销售",problem:"看不见的流失",problemTitle:"不是线索太少\n而是回应太晚",problems:[["5+ 小时","热度正在消退","忙碌之间 好机会悄悄冷却"],["42%","跟进容易断档","散落的消息和手动交接 让客户等在原地"],["先跟谁","机会藏在队列里","读懂意向 才能把精力留给值得的人"]],results:"AI 处理重复工作\n销售专注成交",resultCards:[["更快","客户不用等几个小时才收到回复"],["更准","销售知道谁最值得优先跟进"],["更省","不用每天人工筛选、记录和追踪客户"]],howTitle:"从客户发来消息，到销售接手\n全部自动完成",howCopy:"",steps:[["01","收到客户咨询","客户从网站、广告、WhatsApp、Email 或表单发来咨询"],["02","AI 判断客户意向","自动分析需求、预算、时间和购买意愿"],["03","自动回复并记录","生成个性化回复，同时更新 CRM"],["04","高意向客户交给销售","真正值得跟进的人，马上提醒销售团队"]],demoTitle:"让意向\n自己浮现",demoCopy:"选择一个回答 看 LeadFlow 如何实时读懂客户",video:"90 秒\n看见增长新方式",pricingTitle:"从眼前所需开始\n随业务从容生长",pricingCopy:"不套模板\n每套 LeadFlow 都围绕你的销售路径而生",faqTitle:"常见问题\n一次解答",cta:"好机会\n值得走得更远",ctaCopy:"用 30 分钟 看见更适合你的销售路径"},
  products:{eyebrow:"为生意向前的每一步",title:"把复杂交给 AI\n把时间留给生意",intro:"从获客到服务 从招聘到财务\n每一款产品都为清晰的结果而生",suite:"从一个场景开始",suiteTitle:"先解决一件事\n再改变整家公司",cards:[{name:"AI LeadFlow",tag:"营收智能",desc:"有人咨询 即刻回应\n好机会带着完整背景直达销售",points:["即时识别意向","智能商机评分","持续自动跟进"],live:true},{name:"AI Recruitment",tag:"人才智能",desc:"更快遇见合适的人\n让每一次候选人体验自然顺畅",points:["智能筛选","精准人才清单","面试自动协同"],live:false},{name:"AI Customer Support",tag:"服务智能",desc:"简单问题即刻解决\n复杂需求带着上下文交给团队",points:["全天候响应","智能分流","完整客户视图"],live:false},{name:"AI Invoice Automation",tag:"财务运营",desc:"读取 核验 流转自动完成\n每一笔都清楚 每一步都安心",points:["智能信息提取","自动审批流转","异常主动识别"],live:false}],platform:"一套底座 持续生长",platformTitle:"彼此连接\n才是真正的智能",platformCopy:"数据自然流动 智能持续积累\n每接入一个场景 整个业务都更进一步",pillars:[["01","无缝连接","融入现有系统 不打乱熟悉的节奏"],["02","越用越懂你","每一次互动 都让下一次判断更准"],["03","始终安心","规则清晰 过程透明 决定权始终在你"]],cta:"从一个改变开始\n让生意轻盈向前",ctaCopy:"先选一个最值得改变的场景\n往后的每一步 我们一起设计"},
  footer:"由 AI 驱动，为人而设计"
}
} as const;
export type Locale=keyof typeof messages;
