export const messages = {
 en: {
  common:{products:"Products",how:"How it works",demo:"Demo",pricing:"Pricing",faq:"FAQ",book:"Book a demo",live:"Live",soon:"Coming Soon",learn:"Explore product",home:"Home"},
  home:{badge:"Meet AI LeadFlow · Built for revenue teams",title:"Turn every lead into",accent:"your next customer.",intro:"AI LeadFlow qualifies, scores and follows up with every lead—instantly. So your team only speaks to people ready to buy.",primary:"Book your free demo",secondary:"Watch 90 sec overview",note:"No commitment · Set up in days · Works with your CRM",pipeline:"One intelligent pipeline",salesperson:"Your best salesperson never sleeps.",pipelineCopy:"AI LeadFlow sits between interest and action—responding in seconds, learning what matters, and moving qualified buyers forward.",problem:"The hidden revenue leak",problemTitle:"Your leads aren’t the problem. Your response time is.",problems:[["5+ hrs","Leads wait too long","High-intent prospects go cold while your team is busy doing everything else."],["42%","Follow-ups get missed","Manual handoffs and scattered inboxes make consistent follow-up nearly impossible."],["No signal","Every lead looks equal","Your best opportunities are buried in a queue with everyone else."]],results:"Less chasing. More closing.",howTitle:"From new lead to qualified meeting.",howCopy:"One effortless flow. Built around the tools your team already uses.",steps:[["01","Connect","Plug in your forms, calendar and CRM. No migration. No new process to learn."],["02","Qualify","AI engages every lead instantly, asks the right questions and scores intent."],["03","Convert","Sales-ready opportunities are routed to your team with context and next steps."]],demoTitle:"Watch a lead qualify itself.",demoCopy:"Choose an answer and see AI LeadFlow update the opportunity in real time.",video:"90 seconds to a smarter pipeline.",pricingTitle:"Start focused. Scale freely.",pricingCopy:"Every LeadFlow workspace is configured around your funnel—not a generic template.",faqTitle:"Questions, answered.",cta:"See what AI LeadFlow can do for your pipeline.",ctaCopy:"A focused 30-minute walkthrough, configured around your actual sales process."},
  products:{eyebrow:"AI systems, built to compound",title:"A product suite for the work that moves business forward.",intro:"Purpose-built AI products that remove operational friction, surface better decisions, and let your people focus on work only people can do.",suite:"The product suite",suiteTitle:"Start with one workflow. Build an intelligent company.",cards:[{name:"AI LeadFlow",tag:"Revenue intelligence",desc:"Qualify, score and follow up with every lead instantly—then route sales-ready opportunities with full context.",points:["Instant qualification","Intent scoring","Automated follow-up"],live:true},{name:"AI Recruitment",tag:"Talent intelligence",desc:"Find, screen and coordinate exceptional candidates with a hiring system that never loses momentum.",points:["Candidate screening","Smart shortlists","Interview orchestration"],live:false},{name:"AI Customer Support",tag:"Service intelligence",desc:"Resolve routine questions instantly and give your team the context to handle every complex conversation.",points:["Always-on resolution","Intelligent routing","Unified context"],live:false},{name:"AI Invoice Automation",tag:"Finance operations",desc:"Capture, validate and route invoices automatically, with transparent controls at every step.",points:["Data extraction","Approval workflows","Exception detection"],live:false}],platform:"One intelligent foundation",platformTitle:"Designed as a system. Not a collection of tools.",platformCopy:"Every product shares a scalable architecture for integrations, intelligence, governance and reporting—so each new workflow makes your operation stronger.",pillars:[["01","Connect everywhere","Fit into the systems your teams already trust."],["02","Learn continuously","Turn every interaction into better operational intelligence."],["03","Scale responsibly","Keep humans in control with clear rules and visibility."]],cta:"Build your AI operating layer.",ctaCopy:"Start with the workflow creating the most friction today. We’ll design the path forward."},footer:"Built with AI. Designed for people."},
 zh:{
  common:{products:"产品",how:"运作方式",demo:"体验",pricing:"方案",faq:"常见问题",book:"预约体验",live:"现已推出",soon:"即将推出",learn:"进一步了解",home:"首页"},
  home:{badge:"AI LeadFlow · 为增长团队打造",title:"不错过每一次意向",accent:"把更多线索变成客户",intro:"从首次响应、意向识别到持续跟进，AI LeadFlow 全程自动推进。销售团队只需专注真正值得沟通的机会。",primary:"预约免费体验",secondary:"观看 90 秒介绍",note:"无需长期承诺 · 数天即可上线 · 无缝接入现有 CRM",pipeline:"一套更聪明的增长引擎",salesperson:"好机会从不等待",pipelineCopy:"AI LeadFlow 在客户产生兴趣的那一刻立即响应，读懂每个关键信号，并把成熟商机稳稳交到销售手中。",problem:"增长不该悄悄流失",problemTitle:"线索并不少，及时回应才是关键",problems:[["5+ 小时","等待消磨购买意愿","团队忙于日常事务时，原本炙热的需求也会一点点冷却。"],["42%","跟进常在交接中断档","分散的邮箱与手动流转，让每一次持续触达都变得困难。"],["难辨优先级","真正的机会被淹没","缺少清晰的意向信号，高价值客户只能和普通咨询一起排队。"]],results:"少一点追赶，多一点成交",howTitle:"从一条新线索，到一次高质量会面",howCopy:"一套自然流畅的流程，直接融入团队已经熟悉的工具。",steps:[["01","接入","连接表单、日历和 CRM。无需迁移数据，也无需改变团队习惯。"],["02","识别","AI 即时开启对话，循序了解需求，并持续判断购买意向。"],["03","推进","成熟商机自动送达销售团队，客户背景与下一步建议一目了然。"]],demoTitle:"看见一条线索如何成为商机",demoCopy:"选择不同回答，实时查看 AI LeadFlow 如何判断意向并更新商机。",video:"90 秒，看懂更聪明的增长方式",pricingTitle:"从关键一步开始，随业务从容扩展",pricingCopy:"每个 LeadFlow 工作空间都围绕真实销售路径量身配置，不套用千篇一律的模板。",faqTitle:"你关心的，这里都有答案",cta:"让每一条好线索，都走得更远",ctaCopy:"用 30 分钟了解 AI LeadFlow。我们会结合你的实际销售流程，呈现真正适合团队的方案。"},
  products:{eyebrow:"为长期增长而生的 AI 系统",title:"让真正重要的工作，更快向前",intro:"一系列为企业场景精心打造的 AI 产品，化繁为简、洞察先机，让团队把时间留给更有价值的创造。",suite:"AI 产品矩阵",suiteTitle:"从一个关键流程开始，逐步构建智能企业",cards:[{name:"AI LeadFlow",tag:"营收智能",desc:"即时识别、评估并持续跟进每一条线索，让成熟商机带着完整背景直达销售团队。",points:["即时识别意向","智能商机评分","持续自动跟进"],live:true},{name:"AI Recruitment",tag:"人才智能",desc:"从发现人才到筛选与协调，让优秀候选人的每一步体验都顺畅连贯。",points:["智能筛选","精准人才清单","面试自动协同"],live:false},{name:"AI Customer Support",tag:"服务智能",desc:"常见问题即时解决，复杂需求完整交接，让每一次客户沟通都有始有终。",points:["全天候响应","智能分流","完整客户视图"],live:false},{name:"AI Invoice Automation",tag:"财务运营",desc:"自动读取、核验与流转发票，关键环节清晰可见，异常情况及时掌握。",points:["智能信息提取","自动审批流转","异常主动识别"],live:false}],platform:"统一智能底座",platformTitle:"不是工具的集合，而是一套完整系统",platformCopy:"产品共享同一套可扩展的连接、智能、治理与洞察能力。每增加一个流程，企业的运营体系就更进一步。",pillars:[["01","连接现有工具","自然融入团队信赖的系统，不打乱熟悉的工作方式。"],["02","越用越懂业务","让每一次互动沉淀为洞察，持续优化下一次决策。"],["03","安心规模化","规则清晰、过程透明，让团队始终保有最终掌控。"]],cta:"从今天开始，构建你的 AI 运营体系",ctaCopy:"先解决最影响效率的一个流程。接下来的每一步，我们与你一起设计。"},
  footer:"由 AI 驱动，为人而设计"
}
} as const;
export type Locale=keyof typeof messages;
