export const messages = {
 en: {
  common:{products:"Products",how:"How it works",demo:"Demo",pricing:"Pricing",faq:"FAQ",book:"Book a demo",live:"Live",soon:"Coming Soon",learn:"Explore product",home:"Home"},
  home:{badge:"THE HIDDEN COST OF SLOW RESPONSES",values:["⚡ Faster Response","📈 More Conversions","🎯 Less Revenue Lost"],title:"Reply late.",accent:"Lose deals.",primary:"Book Free Demo",secondary:"Watch 90-sec Demo",pipeline:"One intelligent pipeline",salesperson:"Your best salesperson never sleeps.",pipelineCopy:"AI LeadFlow sits between interest and action—responding in seconds, learning what matters, and moving qualified buyers forward.",problem:"The hidden revenue leak",problemTitle:"Your leads aren’t the problem. Your response time is.",problems:[["5+ hrs","Leads wait too long","High-intent prospects go cold while your team is busy doing everything else."],["42%","Follow-ups get missed","Manual handoffs and scattered inboxes make consistent follow-up nearly impossible."],["No signal","Every lead looks equal","Your best opportunities are buried in a queue with everyone else."]],results:"Less chasing. More closing.",howTitle:"From new lead to qualified meeting.",howCopy:"One effortless flow. Built around the tools your team already uses.",steps:[["01","Connect","Plug in your forms, calendar and CRM. No migration. No new process to learn."],["02","Qualify","AI engages every lead instantly, asks the right questions and scores intent."],["03","Convert","Sales-ready opportunities are routed to your team with context and next steps."]],demoTitle:"Watch a lead qualify itself.",demoCopy:"Choose an answer and see AI LeadFlow update the opportunity in real time.",video:"90 seconds to a smarter pipeline.",impact:{title:"Business Impact",subtitle:"AI LeadFlow doesn't replace your team.\nIt removes repetitive work so your team can focus on closing deals.",cards:[{before:"Customers wait hours",after:"Replies in seconds"},{before:"Every inquiry handled manually",after:"AI handles repetitive conversations"},{before:"Sales chase every customer",after:"Sales focus on high-intent customers"},{before:"Missed opportunities",after:"Every customer gets a response"}],summary:["More conversations.","More opportunities.","More revenue."]},pricingTitle:"Start focused. Scale freely.",pricingCopy:"Every LeadFlow workspace is configured around your funnel—not a generic template.",faqTitle:"Questions, answered.",cta:"See what AI LeadFlow can do for your pipeline.",ctaCopy:"A focused 30-minute walkthrough, configured around your actual sales process."},
  products:{eyebrow:"AI systems, built to compound",title:"A product suite for the work that moves business forward.",intro:"Purpose-built AI products that remove operational friction, surface better decisions, and let your people focus on work only people can do.",suite:"The product suite",suiteTitle:"Start with one workflow. Build an intelligent company.",cards:[{name:"AI LeadFlow",tag:"Revenue intelligence",desc:"Qualify, score and follow up with every lead instantly—then route sales-ready opportunities with full context.",points:["Instant qualification","Intent scoring","Automated follow-up"],live:true},{name:"AI Recruitment",tag:"Talent intelligence",desc:"Find, screen and coordinate exceptional candidates with a hiring system that never loses momentum.",points:["Candidate screening","Smart shortlists","Interview orchestration"],live:false},{name:"AI Customer Support",tag:"Service intelligence",desc:"Resolve routine questions instantly and give your team the context to handle every complex conversation.",points:["Always-on resolution","Intelligent routing","Unified context"],live:false},{name:"AI Invoice Automation",tag:"Finance operations",desc:"Capture, validate and route invoices automatically, with transparent controls at every step.",points:["Data extraction","Approval workflows","Exception detection"],live:false}],platform:"One intelligent foundation",platformTitle:"Designed as a system. Not a collection of tools.",platformCopy:"Every product shares a scalable architecture for integrations, intelligence, governance and reporting—so each new workflow makes your operation stronger.",pillars:[["01","Connect everywhere","Fit into the systems your teams already trust."],["02","Learn continuously","Turn every interaction into better operational intelligence."],["03","Scale responsibly","Keep humans in control with clear rules and visibility."]],cta:"Build your AI operating layer.",ctaCopy:"Start with the workflow creating the most friction today. We’ll design the path forward."},footer:"Built with AI. Designed for people."},
 zh:{
  common:{products:"产品",how:"如何运作",demo:"现场体验",pricing:"方案",faq:"问答",book:"预约演示",live:"现已开放",soon:"敬请期待",learn:"了解产品",home:"首页"},
  home:{badge:"看不见的成交成本",values:["⚡ 更快回应","📈 更多成交","🎯 更少流失"],title:"回应慢了",accent:"成交没了",primary:"预约免费体验",secondary:"观看 90 秒介绍",pipeline:"从兴趣到行动",salesperson:"机会来了\n不必再等",pipelineCopy:"客户刚刚动心 LeadFlow 已经开始行动\n捕捉信号 判断意向 把好机会及时交给销售",problem:"看不见的流失",problemTitle:"不是线索太少\n而是回应太晚",problems:[["5+ 小时","热度正在消退","忙碌之间 好机会悄悄冷却"],["42%","跟进容易断档","散落的消息和手动交接 让客户等在原地"],["先跟谁","机会藏在队列里","读懂意向 才能把精力留给值得的人"]],results:"少一点追赶\n多一点成交",howTitle:"三步\n让商机自然向前",howCopy:"不换系统 不添负担\n从团队熟悉的工作方式开始",steps:[["01","连接","表单 日历 CRM 轻松接入"],["02","读懂","即时对话 捕捉每一个购买信号"],["03","成交","完整背景和下一步建议 直接交给销售"]],demoTitle:"让意向\n自己浮现",demoCopy:"选择一个回答 看 LeadFlow 如何实时读懂客户",video:"90 秒\n看见增长新方式",impact:{title:"真正改变的\n不是工作流程\n而是你的业绩",subtitle:"AI 不取代你的团队。\n它只是接手重复工作，\n让团队把时间留给真正重要的客户。",cards:[{before:"客户等待数小时",after:"几秒内完成回应"},{before:"每条咨询都要人工处理",after:"AI 自动处理重复咨询"},{before:"销售跟进所有客户",after:"销售只专注高意向客户"},{before:"不断错过商机",after:"每位客户都有回应"}],summary:["更多回应","更多机会","更多成交"]},pricingTitle:"从眼前所需开始\n随业务从容生长",pricingCopy:"不套模板\n每套 LeadFlow 都围绕你的销售路径而生",faqTitle:"常见问题\n一次解答",cta:"好机会\n值得走得更远",ctaCopy:"用 30 分钟 看见更适合你的销售路径"},
  products:{eyebrow:"为生意向前的每一步",title:"把复杂交给 AI\n把时间留给生意",intro:"从获客到服务 从招聘到财务\n每一款产品都为清晰的结果而生",suite:"从一个场景开始",suiteTitle:"先解决一件事\n再改变整家公司",cards:[{name:"AI LeadFlow",tag:"营收智能",desc:"有人咨询 即刻回应\n好机会带着完整背景直达销售",points:["即时识别意向","智能商机评分","持续自动跟进"],live:true},{name:"AI Recruitment",tag:"人才智能",desc:"更快遇见合适的人\n让每一次候选人体验自然顺畅",points:["智能筛选","精准人才清单","面试自动协同"],live:false},{name:"AI Customer Support",tag:"服务智能",desc:"简单问题即刻解决\n复杂需求带着上下文交给团队",points:["全天候响应","智能分流","完整客户视图"],live:false},{name:"AI Invoice Automation",tag:"财务运营",desc:"读取 核验 流转自动完成\n每一笔都清楚 每一步都安心",points:["智能信息提取","自动审批流转","异常主动识别"],live:false}],platform:"一套底座 持续生长",platformTitle:"彼此连接\n才是真正的智能",platformCopy:"数据自然流动 智能持续积累\n每接入一个场景 整个业务都更进一步",pillars:[["01","无缝连接","融入现有系统 不打乱熟悉的节奏"],["02","越用越懂你","每一次互动 都让下一次判断更准"],["03","始终安心","规则清晰 过程透明 决定权始终在你"]],cta:"从一个改变开始\n让生意轻盈向前",ctaCopy:"先选一个最值得改变的场景\n往后的每一步 我们一起设计"},
  footer:"由 AI 驱动，为人而设计"
}
} as const;
export type Locale=keyof typeof messages;
