import { Blocks, BriefcaseBusiness, Check, ChevronRight, Headphones, Network, ShieldCheck, Sparkles, UsersRound, Workflow as WorkflowIcon } from "lucide-react";
import { Navigation } from "@/components/layout/navigation";
import { Footer } from "@/components/layout/footer";
import { Button } from "@/components/ui/button";
import { Container } from "@/components/ui/container";
import { Reveal } from "@/components/ui/reveal";
import { SectionHeading } from "@/components/ui/section-heading";
import { Workflow } from "@/components/visuals/workflow";
import { siteConfig } from "@/config/site";

const capabilities=[
 {icon:Sparkles,title:"AI Automation",copy:"Intelligent systems that handle repetitive work accurately, around the clock."},
 {icon:WorkflowIcon,title:"Process Optimization",copy:"Fewer handoffs, faster decisions, and operations designed to move."},
 {icon:Blocks,title:"Custom Workflows",copy:"Automation shaped around your tools, rules, and customer journey."},
 {icon:ShieldCheck,title:"Enterprise Ready",copy:"Reliable architecture with security, control, and scale built in."},
];

export default function Home(){return <><Navigation/><main id="main-content">
<section id="home" className="relative overflow-hidden pb-28 pt-40 sm:pt-48 lg:pb-40 lg:pt-56"><div className="pointer-events-none absolute right-[-8%] top-36 h-[560px] w-[560px] rounded-full bg-[radial-gradient(circle,#f0f6ff_0%,rgba(255,255,255,0)_68%)]"/><Container className="relative grid items-center gap-16 lg:grid-cols-[1.02fr_.98fr] lg:gap-12"><Reveal><p className="mb-7 text-sm font-semibold tracking-[.13em] text-accent uppercase">AI systems. Real business outcomes.</p><h1 className="max-w-[680px] text-balance text-[52px] font-semibold leading-[.98] tracking-[-.06em] text-ink sm:text-7xl lg:text-[78px]">AI Automation<br/>for Modern Businesses.</h1><p className="mt-8 max-w-lg text-xl leading-8 text-muted">Automate repetitive work. Qualify leads faster. Scale without hiring more people.</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><Button href="#products">View Products</Button><Button href="#contact" variant="secondary">Book a Demo</Button></div><p className="mt-8 flex items-center gap-2 text-sm text-muted"><Check className="h-4 w-4 text-accent"/>Designed around your existing workflow.</p></Reveal><Reveal delay={.15}><Workflow/></Reveal></Container></section>

<section id="products" className="scroll-mt-24 bg-[#f5f5f7] py-28 lg:py-40"><Container><Reveal><SectionHeading eyebrow="Products" title="Purpose-built automation that moves work forward." copy="Start with the systems that create immediate leverage. Expand as your business grows."/></Reveal><div className="mt-16 grid gap-5 lg:grid-cols-2"><Reveal className="lg:row-span-2"><article className="group flex h-full min-h-[560px] flex-col overflow-hidden rounded-[32px] bg-white p-7 shadow-[0_1px_0_rgba(0,0,0,.04)] sm:p-10"><div className="flex items-start justify-between gap-4"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-accent text-white"><Network size={23}/></div><span className="rounded-full bg-[#eaf6ee] px-3 py-1.5 text-xs font-semibold text-[#287a3d]">Available</span></div><div className="mt-10"><p className="text-sm font-medium text-accent">V1.0</p><h3 className="mt-2 text-4xl font-semibold tracking-[-.04em] text-ink">AI LeadFlow</h3><p className="mt-4 max-w-md text-lg leading-7 text-muted">Qualify, score, and follow up with every lead—then route the right opportunities directly into your CRM.</p></div><div className="my-10 grid grid-cols-2 gap-3">{["Lead qualification","Intelligent scoring","Follow-up automation","CRM integration"].map(x=><div key={x} className="flex items-center gap-2 rounded-xl bg-[#f5f5f7] p-3 text-sm text-ink"><Check size={15} className="text-accent"/>{x}</div>)}</div><a href="#demo" className="mt-auto inline-flex items-center gap-1 text-sm font-semibold text-accent">Learn More <ChevronRight size={16} className="transition-transform group-hover:translate-x-1"/></a></article></Reveal>
{[{icon:UsersRound,title:"AI Recruitment",copy:"A smarter way to screen, coordinate, and move exceptional candidates forward."},{icon:Headphones,title:"AI Customer Support",copy:"Fast, consistent answers with seamless escalation to the right person."}].map((p,i)=><Reveal key={p.title} delay={i*.08}><article className="rounded-[32px] bg-white p-7 sm:p-9"><div className="flex items-start justify-between"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[#f5f5f7] text-ink"><p.icon size={21}/></div><span className="rounded-full border border-line px-3 py-1.5 text-xs font-medium text-muted">Coming Soon</span></div><h3 className="mt-9 text-2xl font-semibold tracking-[-.03em] text-ink">{p.title}</h3><p className="mt-3 max-w-md leading-7 text-muted">{p.copy}</p></article></Reveal>)}</div></Container></section>

<section className="py-28 lg:py-40"><Container><Reveal><SectionHeading eyebrow="Why Too Yi Hao" title="Automation built around how your business actually works."/></Reveal><div className="mt-16 grid gap-px overflow-hidden rounded-[32px] border border-line bg-line md:grid-cols-2 lg:grid-cols-4">{capabilities.map((x,i)=><Reveal key={x.title} delay={i*.06} className="bg-white"><article className="h-full p-8 lg:min-h-[290px]"><x.icon className="h-7 w-7 text-accent" strokeWidth={1.7}/><h3 className="mt-16 text-xl font-semibold tracking-[-.02em] text-ink">{x.title}</h3><p className="mt-3 text-sm leading-6 text-muted">{x.copy}</p></article></Reveal>)}</div></Container></section>

<section id="demo" className="scroll-mt-24 pb-28 lg:pb-40"><Container><Reveal><div className="relative overflow-hidden rounded-[36px] bg-[#f5f5f7] px-7 py-16 sm:px-14 lg:px-20 lg:py-24"><div className="absolute -right-20 -top-32 h-96 w-96 rounded-full bg-[radial-gradient(circle,rgba(0,113,227,.12),transparent_67%)]"/><div className="relative max-w-2xl"><p className="text-sm font-semibold tracking-[.13em] text-accent uppercase">See it in action</p><h2 className="mt-6 text-balance text-4xl font-semibold tracking-[-.05em] text-ink sm:text-6xl">Experience AI LeadFlow.</h2><p className="mt-6 text-lg leading-8 text-muted">See how leads become qualified opportunities in seconds—not hours.</p><Button href="#contact" className="mt-9">Try Demo</Button></div></div></Reveal></Container></section>

<section id="about" className="scroll-mt-24 border-y border-line py-28 lg:py-40"><Container className="grid gap-14 lg:grid-cols-2 lg:gap-24"><Reveal><p className="text-sm font-semibold tracking-[.13em] text-accent uppercase">About</p><h2 className="mt-6 text-5xl font-semibold tracking-[-.05em] text-ink sm:text-6xl">Too Yi Hao</h2><p className="mt-4 text-xl text-muted">AI Automation Builder</p></Reveal><Reveal delay={.1}><p className="text-balance text-3xl font-medium leading-[1.3] tracking-[-.035em] text-ink sm:text-4xl">Helping businesses eliminate repetitive work using AI.</p><p className="mt-7 max-w-lg text-lg leading-8 text-muted">We design premium automation systems that fit your operation, elevate your customer experience, and give your team more time for meaningful work.</p></Reveal></Container></section>

<section id="contact" className="scroll-mt-24 py-28 lg:py-40"><Container><Reveal><div className="mx-auto max-w-3xl text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[#f5f5f7] text-accent"><BriefcaseBusiness size={24}/></div><h2 className="mt-8 text-5xl font-semibold tracking-[-.055em] text-ink sm:text-7xl">Let’s build what’s next.</h2><p className="mx-auto mt-7 max-w-xl text-lg leading-8 text-muted">Tell us where work slows down. We’ll show you how a thoughtful AI system can move it forward.</p><Button href={siteConfig.bookingHref} className="mt-10">Book a Demo</Button><a href={`mailto:${siteConfig.email}`} className="mt-6 block text-sm text-muted transition-colors hover:text-accent">{siteConfig.email}</a></div></Reveal></Container></section>
</main><Footer/></>}
