"use client";

import Link from "next/link";
import {useState} from "react";
import {ArrowRight,ArrowDown,Check,ChevronDown,Mail,BrainCircuit,MessageCircle,Database,Bell,Plug,Settings2,Play,UserPlus,Layers3} from "lucide-react";
import {Container} from "@/components/ui/container";
import {Reveal} from "@/components/ui/reveal";
import {useI18n} from "@/i18n/provider";

const productPaths=["leadflow","recruiter","supportflow","invoiceflow","meetingflow"];
const products=[
  ["AI LeadFlow","Turn conversations into qualified opportunities.","把每次咨询变成销售机会"],
  ["AI Recruiter","Find and qualify the right candidates.","寻找并筛选合适人才"],
  ["AI SupportFlow","Resolve customer questions at any hour.","随时解决客户问题"],
  ["AI InvoiceFlow","Keep invoices moving without manual chasing.","让发票流程自动推进"],
  ["AI MeetingFlow","Turn every meeting into clear action.","把会议转化为清晰行动"],
];
function Kicker({children}:{children:React.ReactNode}){return <p className="home-kicker">{children}</p>}
function Title({children,className=""}:{children:React.ReactNode,className?:string}){return <h2 className={`home-title ${className}`}>{children}</h2>}

export function Hero(){const{locale}=useI18n();const z=locale==="zh";return <section id="home" className="home-hero"><div className="ambient ambient-a"/><div className="ambient ambient-b"/><Container className="hero-layout"><Reveal className="hero-copy"><Kicker>TOOYIHAO · AI WORKER PLATFORM</Kicker><h1>{z?<>一个平台<br/>无限 <em>AI Worker</em></>:<>One Platform.<br/>Unlimited <em>AI Workers.</em></>}</h1><p>{z?<>选择适合业务的 AI Worker<br/>连接你已经在使用的工具<br/>让重复工作自动完成</>:<>Choose the AI Workers your business needs.<br/>Connect the tools you already use.<br/>Let repetitive work run automatically.</>}</p><div className="home-actions"><Link className="red-button" href="#experience">{z?"开始体验":"Start Experience"}<ArrowRight/></Link><Link className="quiet-button" href="#marketplace">{z?"探索 AI Worker":"Explore AI Workers"}</Link></div></Reveal><Reveal className="ecosystem" delay={.15}><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="core"><span>T</span><b>TOOYIHAO</b><small>AI Worker Core</small></div>{["Respond","Qualify","Analyze","Automate","Update","Notify"].map((x,i)=><div className={`worker-node node-${i}`} key={x}><i/>{x}</div>)}{[[Mail,"Gmail"],[MessageCircle,"WhatsApp"],[Database,"CRM"],[Bell,"Slack"]].map(([Icon,x],i)=>{const I=Icon as typeof Mail;return <div className={`tool-node tool-${i}`} key={x as string}><I/><span>{x as string}</span></div>})}<span className="flow-status"><i/> Workers active</span></Reveal></Container></section>}

export function Vision(){const{locale}=useI18n();const z=locale==="zh";return <section className="home-screen vision"><Container><Reveal><Title>{z?<>一个平台<br/>无限 <em>AI Worker</em></>:<>One Platform.<br/>Unlimited <em>AI Workers.</em></>}</Title><p className="vision-copy">{z?<>为每一种业务而生<br/>由 AI 驱动</>:<>Built for every business.<br/>Powered by AI.</>}</p></Reveal><Reveal className="vision-values">{(z?["节省时间","提升增长","减少错误","轻松扩展"]:["Save Time","Increase Revenue","Improve Accuracy","Scale Effortlessly"]).map((x,i)=><span key={x}><b>0{i+1}</b>{x}</span>)}</Reveal></Container></section>}

export function Marketplace(){const{locale}=useI18n();const z=locale==="zh";return <section id="marketplace" className="home-screen marketplace"><Container><Reveal><Kicker>{z?"发现你的 AI 团队":"EXPLORE THE COLLECTION"}</Kicker><Title>{z?"AI Worker 市集":"AI Worker Marketplace"}</Title><p className="home-subtitle">{z?"选择业务真正需要的 AI Worker":"Choose the AI Worker your business needs."}</p></Reveal><div className="worker-grid">{products.map((p,i)=><Reveal delay={i*.05} key={p[0]}><Link href={`/products/${productPaths[i]}`} className={`worker-card product-accent-${i}`}><div><span className="worker-icon"><Layers3/></span><span className={i===0?"available":"soon"}>{i===0?(z?"现已推出":"Available"):(z?"即将推出":"Coming soon")}</span></div><div><h3>{p[0]}</h3><p>{z?p[2]:p[1]}</p><ArrowRight/></div></Link></Reveal>)}</div></Container></section>}

const flow=[MessageCircle,BrainCircuit,Mail,Database,Bell];
export function FeaturedWorker(){const{locale}=useI18n();const z=locale==="zh";return <section id="featured" className="home-screen featured"><Container className="featured-grid"><Reveal><Kicker>{z?"精选 AI WORKER":"FEATURED AI WORKER"}</Kicker><Title>AI LeadFlow</Title><h3>{z?<>让每一次客户咨询<br/>都不再轻易流失</>:<>Turn every customer conversation<br/>into a sales opportunity.</>}</h3><ul>{(z?["即时响应","AI 意向分析","个性化跟进","自动更新 CRM","通知销售团队"]:["Instant response","AI intent analysis","Personalized follow-up","Automatic CRM update","Sales notification"]).map(x=><li key={x}><Check/>{x}</li>)}</ul><Link className="text-link" href="/products/leadflow">{z?"了解 AI LeadFlow":"Explore AI LeadFlow"}<ArrowRight/></Link></Reveal><Reveal className="flow-composition"><div className="customer-message"><small>{z?"新客户咨询":"NEW CUSTOMER INQUIRY"}</small><p>{z?"你好 我想了解专业版的价格":"Hi, I’d like to know your Pro pricing."}</p><span>Just now</span></div><div className="flow-rail">{flow.map((I,i)=><div className="flow-stage" key={i}><span><I/></span><b>{(z?["收到消息","理解意图","生成回复","更新 CRM","通知销售"]:["Message","AI understands","Reply","CRM updated","Sales notified"])[i]}</b>{i<4&&<i/>}</div>)}</div><div className="reply-card"><span><i/> AI LeadFlow</span><p>{z?"高意向 · 已自动回复 · 已分配销售":"High intent · Replied · Owner assigned"}</p></div></Reveal></Container></section>}

export function InteractiveExperience(){const{locale}=useI18n();const z=locale==="zh";const[input,setInput]=useState(z?"我想了解你们的价格":"I’d like to know your pricing.");const[running,setRunning]=useState(false);const[done,setDone]=useState(false);function run(){if(!input.trim())return;setDone(false);setRunning(true);window.setTimeout(()=>{setRunning(false);setDone(true)},1100)}return <section id="experience" className="home-screen experience"><Container><Reveal className="center-heading"><Kicker>{z?"无需注册 · 直接体验":"INTERACTIVE EXPERIENCE"}</Kicker><Title>{z?"亲自体验 AI LeadFlow":"Try AI LeadFlow"}</Title><p className="home-subtitle">{z?<>输入一条客户咨询<br/>看看 AI 如何判断、回复并推进流程</>:<>Send a sample customer inquiry<br/>and see how AI LeadFlow handles it.</>}</p></Reveal><Reveal className="try-panel"><div className="try-input"><label htmlFor="lead-message">{z?"客户咨询":"Customer inquiry"}</label><textarea id="lead-message" value={input} onChange={e=>setInput(e.target.value)} maxLength={240}/><button onClick={run} disabled={running}>{running?(z?"AI 正在处理":"AI is working"):(z?"运行 AI 工作流":"Run AI workflow")}<Play/></button><small>{z?"模拟体验 不会保存任何数据":"Simulation only · No data is saved"}</small></div><div className={`try-result ${running?"running":""} ${done?"done":""}`} aria-live="polite"><div className="analysis-top"><BrainCircuit/><span><b>{running?(z?"正在分析":"Analyzing"):(z?"AI 分析":"AI analysis")}</b><small>{done?(z?"处理完成":"Complete"):(z?"等待消息":"Ready for a message")}</small></span></div>{[["Intent",z?"价格咨询":"Pricing inquiry"],["Priority",z?"高":"High"],["Reply",z?"已生成个性化回复":"Personalized reply ready"],["CRM",z?"联系人已更新":"Contact updated"],["Sales",z?"已发送通知":"Notification sent"]].map((x,i)=><div className="analysis-row" style={{"--delay":`${i*100}ms`} as React.CSSProperties} key={x[0]}><span>{x[0]}</span><b>{done?x[1]:"—"}</b>{done&&<Check/>}</div>)}</div></Reveal></Container></section>}

export function PlatformSteps(){const{locale}=useI18n();const z=locale==="zh";const labels=z?["注册账号","选择 AI Worker","连接常用工具","配置业务规则","AI 开始工作"]:["Create Account","Choose AI Workers","Connect Your Tools","Configure Your Business","AI Starts Working"];const icons=[UserPlus,Layers3,Plug,Settings2,Play];return <section id="how" className="home-screen platform-steps"><Container><Reveal><Kicker>{z?"简单开始":"HOW IT WORKS"}</Kicker><Title>{z?<>只需 5 步<br/>让 AI 开始工作</>:<>From setup to working AI<br/>in five simple steps.</>}</Title></Reveal><div className="steps-line">{labels.map((x,i)=>{const I=icons[i];return <Reveal className="simple-step" delay={i*.06} key={x}><span>0{i+1}</span><I/><h3>{x}</h3></Reveal>})}</div></Container></section>}

const tools=["Google","Gmail","WhatsApp","HubSpot","Slack","Google Sheets","Microsoft 365","Notion"];
export function Integrations(){const{locale}=useI18n();const z=locale==="zh";return <section id="integrations" className="home-screen integrations"><Container><Reveal className="center-heading"><Kicker>{z?"无缝连接":"INTEGRATIONS"}</Kicker><Title>{z?"连接你已经在用的工具":<>Works with the tools<br/>you already use</>}</Title><p className="home-subtitle">{z?<>不用迁移<br/>不用重新搭建<br/>连接即可开始</>:<>No migration. No complicated setup.<br/>Just connect and start.</>}</p></Reveal><Reveal className="tools-grid">{tools.map((x,i)=><div key={x}><span className={`brand-mark brand-${i}`}>{x[0]}</span><b>{x}</b></div>)}</Reveal></Container></section>}

export function BeforeAfter(){const{locale}=useI18n();const z=locale==="zh";const before=z?["手动回复","手动判断意向","手动录入 CRM","错过跟进"]:["Manual replies","Manual qualification","Manual CRM entry","Missed follow-ups"];const after=z?["AI 即时回复","AI 识别意向","CRM 自动更新","销售只看重要信息"]:["AI replies instantly","AI identifies intent","CRM updates automatically","Sales sees what matters"];return <section className="home-screen transformation"><Container><Reveal className="center-heading"><Title>{z?<>少一点重复工作<br/>多一点真正重要的事</>:<>Less manual work.<br/>More important work.</>}</Title></Reveal><Reveal className="before-after"><div><small>{z?"之前":"BEFORE"}</small>{before.map(x=><p key={x}>{x}</p>)}</div><ArrowRight/><div><small>{z?"之后":"AFTER"}</small>{after.map(x=><p key={x}><Check/>{x}</p>)}</div></Reveal></Container></section>}

export function Pricing(){const{locale}=useI18n();const z=locale==="zh";const plans=[["Starter","$39","1 AI Worker"],["Pro","$99","3 AI Workers"],["Business","$249","Unlimited workflows"]];return <section id="pricing" className="home-screen home-pricing"><Container><Reveal className="center-heading"><Kicker>{z?"简单透明":"PRICING"}</Kicker><Title>{z?"从适合你的方案开始":"Start at your own pace."}</Title></Reveal><div className="plans">{plans.map((p,i)=><Reveal delay={i*.07} key={p[0]}><article className={i===1?"selected":""}>{i===1&&<span className="plan-tag">{z?"推荐":"RECOMMENDED"}</span>}<h3>{p[0]}</h3><p><b>{p[1]}</b><small>/ {z?"月":"month"}</small></p><ul><li><Check/>{p[2]}</li><li><Check/>{z?"自助设置向导":"Self-service setup"}</li><li><Check/>{z?"随时取消":"Cancel anytime"}</li></ul><Link href="/#experience">{z?"选择方案":"Choose Plan"}<ArrowRight/></Link></article></Reveal>)}</div></Container></section>}

const faqs=["What is an AI Worker?","What tools can I connect?","How does setup work?","Can I cancel or upgrade?","Is my data secure?","Can I use multiple AI Workers?","What happens after I subscribe?"];
const answers=["An AI Worker is software that understands, decides and completes a defined business workflow for you.","Connect popular communication, CRM, productivity and business tools. More integrations are added regularly.","Create your workspace, connect tools, set business rules, test the workflow and activate it—all inside the setup wizard.","Yes. Upgrade, change or cancel your plan from your workspace.","Connections use secure authorization and your workflows only access the data needed to complete their task.","Yes. Add specialized AI Workers to the same workspace as your needs grow.","You enter your workspace and follow the guided setup to connect, configure, test and activate your AI Worker."];
export function FAQ(){const{locale}=useI18n();const z=locale==="zh";const qz=["什么是 AI Worker","可以连接哪些工具","设置流程如何运作","可以取消或升级吗","我的数据安全吗","可以使用多个 AI Worker 吗","订阅之后会发生什么"];const[open,setOpen]=useState(0);return <section id="faq" className="home-screen home-faq"><Container className="faq-layout"><Reveal><Kicker>FAQ</Kicker><Title>{z?<>你可能想<br/>了解这些</>:<>Good to<br/>know.</>}</Title></Reveal><Reveal className="clean-accordion">{faqs.map((q,i)=><div key={q}><button onClick={()=>setOpen(open===i?-1:i)} aria-expanded={open===i}><span>{z?qz[i]:q}</span><ChevronDown/></button>{open===i&&<p>{z?["AI Worker 是能够理解 判断并执行特定业务流程的软件","连接常用沟通 CRM 办公和业务工具 平台也会持续增加新集成","创建工作区 连接工具 设置规则 测试流程 然后通过向导启用","可以 随时在工作区升级更换或取消方案","连接采用安全授权 工作流只访问完成任务所需的数据","可以 根据业务需要在同一工作区添加多个专业 AI Worker","进入工作区 按向导完成连接 配置 测试和启用"][i]:answers[i]}</p>}</div>)}</Reveal></Container></section>}

export function FinalCTA(){const{locale}=useI18n();const z=locale==="zh";return <section className="final-cta"><div className="ambient ambient-c"/><Container><Reveal><Title>{z?"准备好建立你的 AI 团队了吗":"Ready to build your AI workforce?"}</Title><Link className="red-button" href="#experience">{z?"开始体验":"Start Experience"}<ArrowRight/></Link><ArrowDown className="final-arrow"/></Reveal></Container></section>}
