"use client";
import { useState } from "react";
import { motion } from "framer-motion";
import { ArrowUpRight, BarChart3, Bell, Check, ChevronDown, CirclePlay, LayoutDashboard, Search, Settings, Sparkles, Users } from "lucide-react";
import { useI18n } from "@/i18n/provider";

export function LeadflowDashboard(){const leads=[['Sarah Chen','Acme Studio','94','Qualified'],['Marcus Reid','Northstar','81','Nurture'],['Elena Rossi','Forma Labs','76','Engaged'],['David Kim','Kinetic','62','New']];return <div className="dashboard-shell"><div className="browser-bar"><i/><i/><i/><span>app.aileadflow.ai</span></div><div className="dashboard-body"><aside className="dash-side"><div className="dash-logo"><Sparkles size={15}/></div>{[LayoutDashboard,Users,BarChart3,Settings].map((I,i)=><div className={`dash-nav ${i===0?'active':''}`} key={i}><I size={17}/></div>)}</aside><div className="dash-main"><div className="dash-top"><div><small>OVERVIEW</small><h3>Good morning, Alex</h3></div><div className="flex items-center gap-2"><button><Search size={16}/></button><button><Bell size={16}/></button><div className="avatar">AK</div></div></div><div className="metric-grid">{[['Qualified leads','184','+24%'],['Meetings booked','68','+18%'],['Avg. response','18 sec','−42%'],['Pipeline value','$284k','+31%']].map((m,i)=><div className="dash-metric" key={m[0]}><div className="flex justify-between"><small>{m[0]}</small><span>{m[2]}</span></div><strong>{m[1]}</strong><div className={`spark spark-${i}`}/></div>)}</div><div className="dash-lower"><div className="lead-table"><div className="table-title"><div><b>Lead intelligence</b><small>Live activity across your pipeline</small></div><button>View all <ArrowUpRight size={12}/></button></div><div className="table-head"><span>LEAD</span><span>SCORE</span><span>STATUS</span></div>{leads.map((l,i)=><div className="table-row" key={l[0]}><div><i>{l[0].split(' ').map(x=>x[0]).join('')}</i><p><b>{l[0]}</b><small>{l[1]}</small></p></div><strong>{l[2]}</strong><span className={`status s${i}`}>{l[3]}</span></div>)}</div><div className="activity"><b>AI activity</b><small>Happening now</small>{[['SC','Sarah reached 94 intent','just now'],['MR','Follow-up sent to Marcus','2m'],['ER','Elena viewed pricing','5m']].map((a,i)=><div className="activity-row" key={a[1]}><i>{a[0]}</i><p>{a[1]}<small>{a[2]}</small></p>{i===0&&<em/>}</div>)}</div></div></div></div><div className="dashboard-float"><span><Sparkles size={13}/> AI INSIGHT</span><b>3 high-intent leads need attention</b><small>Potential pipeline value · $48,000</small></div></div>}

export function LiveDemo(){const {locale}=useI18n();const zh=locale==="zh";const [answer,setAnswer]=useState(0);const options=zh?['30 天内','本季度内','先了解一下']:['Within 30 days','This quarter','Just exploring'];const score=[94,78,42][answer];return <div className="live-demo"><div className="demo-chat"><div className="demo-head"><div><i><Sparkles size={14}/></i><p><b>LeadFlow AI</b><small>{zh?'在线 · 即时回复':'Online · replies instantly'}</small></p></div><span>{zh?'实时体验':'LIVE DEMO'}</span></div><div className="chat-body"><div className="ai-message">{zh?'你好 Sarah 👋 我来帮你找到最适合团队的方案。你希望多久内改善目前的线索流程？':'Hi Sarah! 👋 I can help find the best setup for your team. How soon are you looking to improve your lead process?'}</div><div className="option-list">{options.map((x,i)=><button onClick={()=>setAnswer(i)} className={answer===i?'selected':''} key={x}>{x}<span>{answer===i&&<Check size={14}/>}</span></button>)}</div><div className="typing"><i/><i/><i/> {zh?'AI 正在判断意向':'AI is analyzing intent'}</div></div></div><motion.div className="demo-score" key={answer} initial={{opacity:.5,y:8}} animate={{opacity:1,y:0}}><span>{zh?'实时客户画像':'LIVE LEAD PROFILE'}</span><div className="profile-row"><i>SC</i><p><b>Sarah Chen</b><small>Acme Studio · {zh?'24 人团队':'24 employees'}</small></p></div><div className="demo-ring" style={{'--score':`${score*3.6}deg`} as React.CSSProperties}><div><strong>{score}</strong><small>{zh?'意向值':'INTENT'}</small></div></div><p className="score-label">{score>85?(zh?'值得立即跟进':'Sales-ready'):score>60?(zh?'潜力商机':'Warm opportunity'):(zh?'初步了解':'Early research')}</p><div className="score-facts"><p><span>{zh?'计划周期':'Timeline'}</span><b>{options[answer]}</b></p><p><span>{zh?'建议动作':'Recommended action'}</span><b>{score>85?(zh?'立即预约会面':'Book meeting now'):(zh?'进入持续培育':'Add to nurture')}</b></p></div></motion.div></div>}

export function ProductVideo(){const {locale}=useI18n();const zh=locale==="zh";const [playing,setPlaying]=useState(false);return <button aria-label={zh?"播放 AI LeadFlow 产品介绍":"Play AI LeadFlow product overview"} onClick={()=>setPlaying(!playing)} className={`video-stage ${playing?'playing':''}`}><div className="video-grid"/><div className="video-ui"><div className="video-side"/><div className="video-chart"><span>Qualified pipeline</span><strong>$284,000</strong><div className="chart-bars">{[30,45,38,58,65,61,82,94].map((h,i)=><i style={{height:`${h}%`}} key={i}/>)}</div></div><div className="video-leads">{['Sarah Chen · 94','Marcus Reid · 81','Elena Rossi · 76'].map(x=><p key={x}>{x}<Check size={13}/></p>)}</div></div><div className="video-overlay"><span className="play-button">{playing?<span className="pause">Ⅱ</span>:<CirclePlay/>}</span><p>{playing?(zh?'正在播放产品介绍':'Product tour playing'):(zh?'看看 AI LeadFlow 如何工作':'See AI LeadFlow in action')}</p><small>1:30</small></div></button>}

const faqsEn=[['Will this replace my sales team?','No. LeadFlow removes repetitive qualification and follow-up so your team can spend more time on conversations that require a human.'],['Does it work with our existing CRM?','Yes. LeadFlow is designed to connect with modern CRMs, forms, calendars and email tools. We map the integration during onboarding.'],['How quickly can we launch?','Most teams can launch an initial workflow in days, depending on integrations and qualification complexity.'],['Will the AI sound like our brand?','Yes. We configure tone, messaging, guardrails and escalation rules around your brand and sales process.'],['How is pricing determined?','Pricing reflects lead volume, integrations and workflow complexity. Book a demo and we’ll provide a clear, tailored quote.']];
const faqsZh=[['AI 会取代销售团队吗','不会。LeadFlow 接手重复的识别与跟进工作，让销售把更多时间留给真正需要人的判断与沟通。'],['可以接入现有 CRM 吗','可以。LeadFlow 能连接主流 CRM、表单、日历与邮件工具。上线前，我们会与你一起梳理并完成集成。'],['多久可以上线','大多数团队可在数天内启用首个流程，具体时间取决于集成范围与意向判断规则。'],['AI 的表达符合品牌调性吗','当然。我们会根据品牌与销售流程，细致配置语气、话术、边界与人工接管规则。'],['如何确定价格','方案会综合线索量、集成范围与流程复杂度。预约体验后，我们会提供清晰、适合你的报价。']];
export function FAQ(){const {locale}=useI18n();const [open,setOpen]=useState(0);const faqs=locale==="zh"?faqsZh:faqsEn;return <div className="faq-list">{faqs.map((f,i)=><div className="faq-item" key={f[0]}><button aria-expanded={open===i} onClick={()=>setOpen(open===i?-1:i)}><span>{f[0]}</span><ChevronDown className={open===i?'rotate':''}/></button>{open===i&&<motion.p initial={{opacity:0,y:-5}} animate={{opacity:1,y:0}}>{f[1]}</motion.p>}</div>)}</div>}
