"use client";
import { useState } from "react";
import { motion } from "framer-motion";
import { ArrowUpRight, BarChart3, Bell, Check, ChevronDown, CirclePlay, LayoutDashboard, Search, Settings, Sparkles, Users } from "lucide-react";

export function LeadflowDashboard(){const leads=[['Sarah Chen','Acme Studio','94','Qualified'],['Marcus Reid','Northstar','81','Nurture'],['Elena Rossi','Forma Labs','76','Engaged'],['David Kim','Kinetic','62','New']];return <div className="dashboard-shell"><div className="browser-bar"><i/><i/><i/><span>app.aileadflow.ai</span></div><div className="dashboard-body"><aside className="dash-side"><div className="dash-logo"><Sparkles size={15}/></div>{[LayoutDashboard,Users,BarChart3,Settings].map((I,i)=><div className={`dash-nav ${i===0?'active':''}`} key={i}><I size={17}/></div>)}</aside><div className="dash-main"><div className="dash-top"><div><small>OVERVIEW</small><h3>Good morning, Alex</h3></div><div className="flex items-center gap-2"><button><Search size={16}/></button><button><Bell size={16}/></button><div className="avatar">AK</div></div></div><div className="metric-grid">{[['Qualified leads','184','+24%'],['Meetings booked','68','+18%'],['Avg. response','18 sec','−42%'],['Pipeline value','$284k','+31%']].map((m,i)=><div className="dash-metric" key={m[0]}><div className="flex justify-between"><small>{m[0]}</small><span>{m[2]}</span></div><strong>{m[1]}</strong><div className={`spark spark-${i}`}/></div>)}</div><div className="dash-lower"><div className="lead-table"><div className="table-title"><div><b>Lead intelligence</b><small>Live activity across your pipeline</small></div><button>View all <ArrowUpRight size={12}/></button></div><div className="table-head"><span>LEAD</span><span>SCORE</span><span>STATUS</span></div>{leads.map((l,i)=><div className="table-row" key={l[0]}><div><i>{l[0].split(' ').map(x=>x[0]).join('')}</i><p><b>{l[0]}</b><small>{l[1]}</small></p></div><strong>{l[2]}</strong><span className={`status s${i}`}>{l[3]}</span></div>)}</div><div className="activity"><b>AI activity</b><small>Happening now</small>{[['SC','Sarah reached 94 intent','just now'],['MR','Follow-up sent to Marcus','2m'],['ER','Elena viewed pricing','5m']].map((a,i)=><div className="activity-row" key={a[1]}><i>{a[0]}</i><p>{a[1]}<small>{a[2]}</small></p>{i===0&&<em/>}</div>)}</div></div></div></div><div className="dashboard-float"><span><Sparkles size={13}/> AI INSIGHT</span><b>3 high-intent leads need attention</b><small>Potential pipeline value · $48,000</small></div></div>}

export function LiveDemo(){const [answer,setAnswer]=useState(0);const options=['Within 30 days','This quarter','Just exploring'];const score=[94,78,42][answer];return <div className="live-demo"><div className="demo-chat"><div className="demo-head"><div><i><Sparkles size={14}/></i><p><b>LeadFlow AI</b><small>Online · replies instantly</small></p></div><span>LIVE DEMO</span></div><div className="chat-body"><div className="ai-message">Hi Sarah! 👋 I can help find the best setup for your team. How soon are you looking to improve your lead process?</div><div className="option-list">{options.map((x,i)=><button onClick={()=>setAnswer(i)} className={answer===i?'selected':''} key={x}>{x}<span>{answer===i&&<Check size={14}/>}</span></button>)}</div><div className="typing"><i/><i/><i/> AI is analyzing intent</div></div></div><motion.div className="demo-score" key={answer} initial={{opacity:.5,y:8}} animate={{opacity:1,y:0}}><span>LIVE LEAD PROFILE</span><div className="profile-row"><i>SC</i><p><b>Sarah Chen</b><small>Acme Studio · 24 employees</small></p></div><div className="demo-ring" style={{'--score':`${score*3.6}deg`} as React.CSSProperties}><div><strong>{score}</strong><small>INTENT</small></div></div><p className="score-label">{score>85?'Sales-ready':score>60?'Warm opportunity':'Early research'}</p><div className="score-facts"><p><span>Timeline</span><b>{options[answer]}</b></p><p><span>Recommended action</span><b>{score>85?'Book meeting now':'Add to nurture'}</b></p></div></motion.div></div>}

export function ProductVideo(){const [playing,setPlaying]=useState(false);return <button aria-label="Play AI LeadFlow product overview" onClick={()=>setPlaying(!playing)} className={`video-stage ${playing?'playing':''}`}><div className="video-grid"/><div className="video-ui"><div className="video-side"/><div className="video-chart"><span>Qualified pipeline</span><strong>$284,000</strong><div className="chart-bars">{[30,45,38,58,65,61,82,94].map((h,i)=><i style={{height:`${h}%`}} key={i}/>)}</div></div><div className="video-leads">{['Sarah Chen · 94','Marcus Reid · 81','Elena Rossi · 76'].map(x=><p key={x}>{x}<Check size={13}/></p>)}</div></div><div className="video-overlay"><span className="play-button">{playing?<span className="pause">Ⅱ</span>:<CirclePlay/>}</span><p>{playing?'Product tour playing':'See AI LeadFlow in action'}</p><small>1:30</small></div></button>}

const faqs=[['Will this replace my sales team?','No. LeadFlow removes repetitive qualification and follow-up so your team can spend more time on conversations that require a human.'],['Does it work with our existing CRM?','Yes. LeadFlow is designed to connect with modern CRMs, forms, calendars and email tools. We map the integration during onboarding.'],['How quickly can we launch?','Most teams can launch an initial workflow in days, depending on integrations and qualification complexity.'],['Will the AI sound like our brand?','Yes. We configure tone, messaging, guardrails and escalation rules around your brand and sales process.'],['How is pricing determined?','Pricing reflects lead volume, integrations and workflow complexity. Book a demo and we’ll provide a clear, tailored quote.']];
export function FAQ(){const [open,setOpen]=useState(0);return <div className="faq-list">{faqs.map((f,i)=><div className="faq-item" key={f[0]}><button aria-expanded={open===i} onClick={()=>setOpen(open===i?-1:i)}><span>{f[0]}</span><ChevronDown className={open===i?'rotate':''}/></button>{open===i&&<motion.p initial={{opacity:0,y:-5}} animate={{opacity:1,y:0}}>{f[1]}</motion.p>}</div>)}</div>}
