"use client";
import { useEffect, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowRight, ArrowUpRight, BarChart3, Bell, Check, ChevronDown, CirclePlay, Database, LayoutDashboard, LoaderCircle, MessageSquareText, Search, Send, Settings, Sparkles, Users, Zap } from "lucide-react";
import { useI18n } from "@/i18n/provider";

export function LiveAICanvas(){
  const {locale}=useI18n(); const zh=locale==="zh"; const [elapsed,setElapsed]=useState(0);
  useEffect(()=>{const started=performance.now();const timer=window.setInterval(()=>setElapsed((performance.now()-started)%13800),50);return()=>window.clearInterval(timer)},[]);
  const t=elapsed, score=t<3000?12:t<3400?35:t<3800?57:t<4200?79:94, priority=t<3400?(zh?"低":"Low"):t<4200?(zh?"中":"Medium"):(zh?"高":"High");
  const reply=zh?"您好！感谢您的咨询。我们的方案会根据团队规模和需求定制。我很乐意为您介绍价格选项。":"Hi! Thanks for reaching out. Our plans are tailored to your team and goals. I’d be happy to walk you through the pricing options.";
  const typed=reply.slice(0,Math.max(0,Math.floor((t-7200)/22))), done=(at:number)=>t>=at, working=(from:number,to:number)=>t>=from&&t<to;
  return <div className={`ai-canvas ${t>=11200&&t<13200?'is-complete':''} ${t>=13200?'is-resetting':''}`} aria-label={zh?"实时 AI 工作流程演示":"Live AI workflow demonstration"}>
    <div className="canvas-top"><div><span className="canvas-logo"><Sparkles size={14}/></span><b>AI LeadFlow</b></div><span className="canvas-live"><i/>{zh?"实时运行":"LIVE"}</span></div>
    <div className="canvas-content"><div className="canvas-message"><span><MessageSquareText size={13}/>{zh?"新客户咨询":"INCOMING MESSAGE"}</span><p>{zh?<>你好，<br/>我想了解你们的价格。</>:<>Hi,<br/>I&apos;d like to know your pricing.</>}</p><small>Sarah Chen · Acme Studio <em>{zh?"刚刚":"Just now"}</em></small></div>
      <div className="canvas-engine"><div className="engine-head"><div className={t<2600?"thinking":""}><Sparkles size={15}/></div><p><b>{working(1000,1900)?(zh?"正在读取消息…":"Reading message..."):working(1900,2800)?(zh?"正在分析客户…":"Analyzing customer..."):(zh?"AI 工作流":"AI workflow")}</b><small>{zh?"自主执行中":"Working autonomously"}</small></p></div>
        <div className="engine-grid"><div className={`canvas-score ${done(2800)?'visible':''}`}><span>{zh?"线索评分":"LEAD SCORE"}</span><strong>{score}</strong><div><i style={{width:`${score}%`}}/></div><small className="priority">{priority} {zh?"优先级":"priority"}</small></div>
          <div className={`canvas-tasks ${done(4500)?'visible':''}`}><span><Database size={12}/>{zh?"CRM 实时同步":"CRM · LIVE SYNC"}</span>{[["Creating Contact...",5000],["Assigning Sales Owner...",5700],["Updating Pipeline...",6400]].map(([label,at])=><p key={label as string}>{zh?({"Creating Contact...":"正在创建联系人…","Assigning Sales Owner...":"正在分配销售负责人…","Updating Pipeline...":"正在更新管道…"}[label as string]):label}{done(at as number)?<Check size={13}/>:<LoaderCircle className="lab-spinner" size={13}/>}</p>)}</div></div>
        <div className={`canvas-reply ${done(7100)?'visible':''}`}><span><Sparkles size={12}/>{zh?"AI 生成回复":"AI GENERATED REPLY"}</span><p>{typed}<i/></p><small className={done(10100)?"sent":""}>{done(10100)?<><Check size={12}/>{zh?"邮件已发送":"Email sent"}</>:<>{zh?"正在撰写…":"Writing naturally..."}</>}</small></div>
        <div className={`canvas-notification ${done(10600)?'visible':''}`}><span><Bell size={14}/></span><p><b>{zh?"高意向客户":"High-intent lead"}</b><small>{zh?"Sarah 的评分达到 94，销售已通知。":"Sarah reached 94. Sales has been notified."}</small></p><Check size={14}/></div>
      </div><div className="canvas-complete"><div className="complete-check"><Check size={22}/></div><p className="complete-title">{zh?"工作完成":"Work complete"}</p><div className="complete-list"><span><Check/> {zh?"CRM 已更新":"CRM Updated"}</span><span><Check/> {zh?"邮件已发送":"Email Sent"}</span><span><Check/> {zh?"销售已通知":"Sales Notified"}</span></div><div className="complete-time"><small>{zh?"完成用时":"Completed in"}</small><strong>11.2s</strong></div><p className="complete-caption">{zh?<>竞争对手还在回复时，<br/>AI 已经完成了。</>:<>While your competitors<br/>are still typing.</>}</p></div></div>
    <div className="canvas-progress"><i style={{width:`${Math.min(t/11200*100,100)}%`}}/></div>
  </div>
}

export function LeadflowDashboard(){const leads=[['Sarah Chen','Acme Studio','94','Qualified'],['Marcus Reid','Northstar','81','Nurture'],['Elena Rossi','Forma Labs','76','Engaged'],['David Kim','Kinetic','62','New']];return <div className="dashboard-shell"><div className="browser-bar"><i/><i/><i/><span>app.aileadflow.ai</span></div><div className="dashboard-body"><aside className="dash-side"><div className="dash-logo"><Sparkles size={15}/></div>{[LayoutDashboard,Users,BarChart3,Settings].map((I,i)=><div className={`dash-nav ${i===0?'active':''}`} key={i}><I size={17}/></div>)}</aside><div className="dash-main"><div className="dash-top"><div><small>OVERVIEW</small><h3>Good morning, Alex</h3></div><div className="flex items-center gap-2"><button><Search size={16}/></button><button><Bell size={16}/></button><div className="avatar">AK</div></div></div><div className="metric-grid">{[['Qualified leads','184','+24%'],['Meetings booked','68','+18%'],['Avg. response','18 sec','−42%'],['Pipeline value','$284k','+31%']].map((m,i)=><div className="dash-metric" key={m[0]}><div className="flex justify-between"><small>{m[0]}</small><span>{m[2]}</span></div><strong>{m[1]}</strong><div className={`spark spark-${i}`}/></div>)}</div><div className="dash-lower"><div className="lead-table"><div className="table-title"><div><b>Lead intelligence</b><small>Live activity across your pipeline</small></div><button>View all <ArrowUpRight size={12}/></button></div><div className="table-head"><span>LEAD</span><span>SCORE</span><span>STATUS</span></div>{leads.map((l,i)=><div className="table-row" key={l[0]}><div><i>{l[0].split(' ').map(x=>x[0]).join('')}</i><p><b>{l[0]}</b><small>{l[1]}</small></p></div><strong>{l[2]}</strong><span className={`status s${i}`}>{l[3]}</span></div>)}</div><div className="activity"><b>AI activity</b><small>Happening now</small>{[['SC','Sarah reached 94 intent','just now'],['MR','Follow-up sent to Marcus','2m'],['ER','Elena viewed pricing','5m']].map((a,i)=><div className="activity-row" key={a[1]}><i>{a[0]}</i><p>{a[1]}<small>{a[2]}</small></p>{i===0&&<em/>}</div>)}</div></div></div></div><div className="dashboard-float"><span><Sparkles size={13}/> AI INSIGHT</span><b>3 high-intent leads need attention</b><small>Potential pipeline value · $48,000</small></div></div>}

export function LiveDemo(){
  const {locale}=useI18n();
  const zh=locale==="zh";
  type IntentLevel="low"|"medium"|"high";
  type Scenario={text:string;zh:string;score:number;level:IntentLevel};
  const industries:{id:string;label:string;zh:string;emoji:string;scenarios:Scenario[]}[]=[
    {id:"restaurant",label:"Restaurant",zh:"餐厅",emoji:"🍽",scenarios:[
      {text:"Do you have a table tonight?",zh:"今晚还有桌位吗？",score:78,level:"medium"},{text:"Can I book for 8 people?",zh:"可以预订 8 人桌吗？",score:84,level:"medium"},{text:"Is today's special still available?",zh:"今天的特色菜还有吗？",score:34,level:"low"},{text:"Are you open now?",zh:"你们现在营业吗？",score:27,level:"low"}]},
    {id:"gym",label:"Gym",zh:"健身房",emoji:"🏋️",scenarios:[
      {text:"How much is membership?",zh:"会员费用是多少？",score:64,level:"medium"},{text:"Can I try a free class?",zh:"可以免费试课吗？",score:73,level:"medium"},{text:"Is personal training available?",zh:"有私人教练服务吗？",score:38,level:"low"},{text:"Do you have monthly plans?",zh:"有月付方案吗？",score:59,level:"medium"}]},
    {id:"property",label:"Property",zh:"房产",emoji:"🏠",scenarios:[
      {text:"Is this unit still available?",zh:"这个单位还在售吗？",score:39,level:"low"},{text:"Can I arrange a viewing?",zh:"可以安排看房吗？",score:82,level:"medium"},{text:"What is the starting price?",zh:"起售价是多少？",score:67,level:"medium"},{text:"Is there any promotion?",zh:"目前有优惠吗？",score:58,level:"medium"}]},
    {id:"b2b",label:"B2B",zh:"企业服务",emoji:"💼",scenarios:[
      {text:"Can you send a quotation?",zh:"可以发送一份报价吗？",score:69,level:"medium"},{text:"We'd like to discuss cooperation.",zh:"我们想洽谈合作。",score:93,level:"high"},{text:"Our company is interested.",zh:"我们公司对此有兴趣。",score:91,level:"high"},{text:"Can we schedule a meeting?",zh:"可以安排一次会议吗？",score:96,level:"high"},{text:"We'd like to purchase 500 units.",zh:"我们想采购 500 件。",score:99,level:"high"}]},
  ];
  const [industry,setIndustry]=useState(industries[0].id);
  const [message,setMessage]=useState("");
  const [step,setStep]=useState(-1);
  const [selection,setSelection]=useState<Scenario>({text:"",zh:"",score:62,level:"medium"});
  const activeIndustry=industries.find(item=>item.id===industry)!;
  const workflow={
    low:[{label:zh?"正在读取…":"Reading…",icon:MessageSquareText},{label:zh?"意向识别…":"Intent Detection…",icon:Sparkles},{label:zh?"CRM 已创建":"CRM Created",icon:Database}],
    medium:[{label:zh?"正在读取…":"Reading…",icon:MessageSquareText},{label:zh?"意向识别…":"Intent Detection…",icon:Sparkles},{label:zh?"线索已识别…":"Lead Qualified…",icon:BarChart3},{label:zh?"CRM 已创建…":"CRM Created…",icon:Database},{label:zh?"邮件已生成":"Email Generated",icon:Send}],
    high:[{label:zh?"正在读取…":"Reading…",icon:MessageSquareText},{label:zh?"意向识别…":"Intent Detection…",icon:Sparkles},{label:`${zh?"线索评分":"Lead Score"} ${selection.score}`,icon:BarChart3},{label:zh?"高优先级":"Priority High",icon:Zap},{label:zh?"CRM 已创建":"CRM Created",icon:Database},{label:zh?"邮件已发送":"Email Sent",icon:Send},{label:zh?"销售已通知":"Sales Notified",icon:Bell}],
  };
  const milestones=workflow[selection.level];
  const running=step>=0&&step<milestones.length;
  useEffect(()=>{if(!running)return;const timer=window.setTimeout(()=>setStep(current=>current+1),850);return()=>window.clearTimeout(timer)},[step,running,milestones.length]);
  const reset=()=>{setStep(-1);setMessage("")};
  const start=(scenario?:Scenario)=>{const chosen=scenario??{text:message,zh:message,score:62,level:"medium" as IntentLevel};if(scenario)setMessage(zh?scenario.zh:scenario.text);setSelection(chosen);setStep(0)};
  const priority=selection.level==="high"?(zh?"高优先级":"High priority"):selection.level==="medium"?(zh?"中优先级":"Medium priority"):(zh?"低优先级":"Low priority");
  return <div className="leadflow-lab">
    <div className="lab-toolbar"><div><span className="lab-mark"><Sparkles size={15}/></span><p><b>AI LeadFlow</b><small>{zh?"智能线索工作台":"Intelligent lead workspace"}</small></p></div><span className="lab-live"><i/>{zh?"系统在线":"SYSTEM ONLINE"}</span></div>
    <div className="lab-grid">
      <form className="lab-form" onSubmit={e=>{e.preventDefault();start()}}>
        <div className="lab-form-title"><span>01</span><div><h3>{zh?"输入客户咨询":"Paste a customer message"}</h3><p>{zh?"看看 AI 如何从第一句话开始接手。":"Watch AI take it from the very first word."}</p></div></div>
        <div className="industry-tabs" role="tablist" aria-label={zh?"选择行业":"Choose an industry"}>{industries.map(item=><button type="button" role="tab" aria-selected={industry===item.id} className={industry===item.id?"active":""} onClick={()=>{setIndustry(item.id);setStep(-1)}} key={item.id}><span>{item.emoji}</span>{zh?item.zh:item.label}</button>)}</div>
        <AnimatePresence mode="wait"><motion.div className="scenario-list" key={industry} initial={{opacity:0,y:5}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-5}} transition={{duration:.2}}>{activeIndustry.scenarios.map(scenario=><button type="button" className={message===(zh?scenario.zh:scenario.text)?"active":""} disabled={running} onClick={()=>start(scenario)} key={scenario.text}>{zh?scenario.zh:scenario.text}<ArrowRight size={13}/></button>)}</motion.div></AnimatePresence>
        <label>{zh?"客户消息":"Customer Message"}<textarea value={message} onChange={e=>setMessage(e.target.value.slice(0,500))} placeholder={zh?"选择上方的真实咨询，或输入一条消息。":"Choose a real inquiry above, or type your own."} required disabled={running}/><span className="character-count">{message.length}/500</span></label>
        <button className="lab-analyze" disabled={running||!message.trim()}>{running?<><LoaderCircle className="lab-spinner" size={17}/>{zh?"AI 正在工作…":"AI is working…"}</>:<><Sparkles size={17}/>{zh?"立即体验":"Watch AI Work"}<ArrowRight size={16}/></>}</button>
        <p className="lab-note"><span>✦</span>{zh?"这是模拟体验，不会保存或发送任何数据。":"Interactive demo only. No data is saved or sent."}</p>
      </form>
      <div className={`lab-results ${step<0?'is-empty':''}`} aria-live="polite">
        {step<0?<div className="lab-empty"><div><Sparkles/></div><h3>{zh?"AI 已准备就绪":"AI is ready"}</h3><p>{zh?"输入客户咨询并点击“立即体验”，观看完整流程。":"Paste a message and click Watch AI Work to see the full workflow."}</p><div className="empty-lines"><i/><i/><i/></div></div>:<>
          <div className="result-head"><div><span className={running?"processing":"complete"}>{running?<LoaderCircle size={12}/>:<Check size={12}/>} {running?(zh?"AI 正在工作":"AI WORKING"):(zh?"流程完成":"WORKFLOW COMPLETE")}</span><h3>{zh?"实时工作流":"Live workflow"}</h3></div><span className="result-time">00:{String(Math.min(step+1,milestones.length)).padStart(2,"0")}</span></div>
          <div className="workflow-track">{milestones.map((item,i)=>{const Icon=item.icon;const active=i<=step;return <motion.div className={`workflow-row ${active?'active':''}`} initial={{opacity:.25}} animate={{opacity:active?1:.25,x:i===step?[0,3,0]:0}} transition={{duration:.35}} key={item.label}><span className="workflow-icon">{active&&i<step?<Check size={14}/>:i===step&&running?<LoaderCircle className="lab-spinner" size={14}/>:<Icon size={14}/>}</span><p>{item.label}</p>{i<step&&<small>{zh?"完成":"Done"}</small>}</motion.div>})}</div>
          <AnimatePresence>{step>=1&&<motion.div className={`result-summary intent-${selection.level}`} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}}><div className="score-card"><span>{zh?"线索评分":"LEAD SCORE"}</span><strong>{selection.score}<small>/100</small></strong><div className="score-bar"><i style={{width:`${selection.score}%`}}/></div></div><motion.div className="priority-card" initial={{opacity:0,x:8}} animate={{opacity:1,x:0}}><span>{zh?"优先级":"PRIORITY"}</span><strong><i/>{priority}</strong><small>{selection.level==="high"?(zh?"建议 5 分钟内跟进":"Follow up within 5 min"):(zh?"AI 自动处理并记录":"AI handling and logging")}</small></motion.div></motion.div>}</AnimatePresence>
          {step===milestones.length&&<motion.div className={`result-success intent-${selection.level}`} initial={{opacity:0,scale:.98}} animate={{opacity:1,scale:1}}><span><Check size={14}/></span><p><b>{zh?"工作流程完成":"Workflow complete"}</b><small>{milestones.slice(2).map(item=>item.label.replace("…","")).join(" · ")}</small></p><button type="button" onClick={reset}>{zh?"再试一次":"Try again"}</button></motion.div>}
        </>}
      </div>
    </div>
  </div>
}

export function ProductVideo(){const {locale}=useI18n();const zh=locale==="zh";const [playing,setPlaying]=useState(false);return <button aria-label={zh?"播放 AI LeadFlow 产品介绍":"Play AI LeadFlow product overview"} onClick={()=>setPlaying(!playing)} className={`video-stage ${playing?'playing':''}`}><div className="video-grid"/><div className="video-ui"><div className="video-side"/><div className="video-chart"><span>Qualified pipeline</span><strong>$284,000</strong><div className="chart-bars">{[30,45,38,58,65,61,82,94].map((h,i)=><i style={{height:`${h}%`}} key={i}/>)}</div></div><div className="video-leads">{['Sarah Chen · 94','Marcus Reid · 81','Elena Rossi · 76'].map(x=><p key={x}>{x}<Check size={13}/></p>)}</div></div><div className="video-overlay"><span className="play-button">{playing?<span className="pause">Ⅱ</span>:<CirclePlay/>}</span><p>{playing?(zh?'正在播放产品介绍':'Product tour playing'):(zh?'看看 AI LeadFlow 如何工作':'See AI LeadFlow in action')}</p><small>1:30</small></div></button>}

const faqsEn=[['Will this replace my sales team?','No. LeadFlow removes repetitive qualification and follow-up so your team can spend more time on conversations that require a human.'],['Does it work with our existing CRM?','Yes. LeadFlow is designed to connect with modern CRMs, forms, calendars and email tools. We map the integration during onboarding.'],['How quickly can we launch?','Most teams can launch an initial workflow in days, depending on integrations and qualification complexity.'],['Will the AI sound like our brand?','Yes. We configure tone, messaging, guardrails and escalation rules around your brand and sales process.'],['How is pricing determined?','Pricing reflects lead volume, integrations and workflow complexity. Book a demo and we’ll provide a clear, tailored quote.']];
const faqsZh=[['会取代销售团队吗','不会 LeadFlow 接手重复的识别和跟进 让销售专注判断 关系和成交'],['现有 CRM 还能继续用吗','当然 主流 CRM 表单 日历和邮件工具都可接入 上线前我们会一起完成配置'],['多久能够上线','多数团队几天即可启用首个流程 实际时间取决于接入范围和意向规则'],['说话方式像我们的品牌吗','会 我们将品牌语气 销售话术 服务边界和人工接管规则逐一配置'],['如何确定方案','根据线索量 接入范围和流程复杂度灵活设计 演示后你会收到一份清晰方案']];
export function FAQ(){const {locale}=useI18n();const [open,setOpen]=useState(0);const faqs=locale==="zh"?faqsZh:faqsEn;return <div className="faq-list">{faqs.map((f,i)=><div className="faq-item" key={f[0]}><button aria-expanded={open===i} onClick={()=>setOpen(open===i?-1:i)}><span>{f[0]}</span><ChevronDown className={open===i?'rotate':''}/></button>{open===i&&<motion.p initial={{opacity:0,y:-5}} animate={{opacity:1,y:0}}>{f[1]}</motion.p>}</div>)}</div>}
